version: '2'

networks:
  devhyperledger:

services:
  orderer.${ordererDomain}:
    container_name: orderer.${ordererDomain}
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/devnetwork/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=${ordererName}MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/devnetwork/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - ./config/:/etc/hyperledger/devnetwork/configtx
      - ./crypto-config/ordererOrganizations/${ordererDomain}/orderers/orderer.${ordererDomain}/:/etc/hyperledger/devnetwork/orderer
    networks:
      - devhyperledger

${PEER_COMPOSE}