  ca.${peerDomain}:
    container_name: ca_${peerDomain}
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_${peerDomain}
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.${peerDomain}-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CA_PRIVATE_KEY}
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/${peerDomain}/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./config/ca-server/ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    networks:
      - devhyperledger

  peer0.${peerDomain}:
    container_name: peer0.${peerDomain}
    image: hyperledger/fabric-peer
    environment:
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      # CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_${NETWORK}
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=networks_devhyperledger
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/devnetwork/users/Admin@${peerDomain}/msp # /etc/hyperledger/devnetwork/peer/msp # TODO: test change location
      # - CORE_PEER_TLS_ENABLED=true
      # - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # ---------
      - CORE_PEER_ID=peer0.${peerDomain}
      - CORE_PEER_LOCALMSPID=${peerName}MSP
      - CORE_PEER_ADDRESS=peer0.${peerDomain}:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./config:/etc/hyperledger/devnetwork/configtx
      - ./crypto-config/peerOrganizations/${peerDomain}/peers/peer0.${peerDomain}/:/etc/hyperledger/devnetwork/peer
      - ./crypto-config/peerOrganizations/${peerDomain}/users/:/etc/hyperledger/devnetwork/users
    depends_on:
      - orderer.${ordererDomain}
    networks:
    - devhyperledger

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.${peerDomain}:7051
      - CORE_PEER_LOCALMSPID=${peerName}MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/devnetwork/users/Admin@${peerDomain}/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/${peerDomain}/users/:/etc/hyperledger/devnetwork/users
      - ./../chaincode/:/opt/gopath/src/github.com
    networks:
    - devhyperledger